set number
set ru
set hls
set is
set encoding=utf-8
syntax on

set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'fatih/vim-go'

call vundle#end()
filetype plugin indent on


